services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    networks:
      - app_network

  nestjs:
    build:
      context: ./be
    container_name: nestjs_app
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USERNAME: your_db_user
      DB_PASSWORD: your_db_password
      DB_DATABASE: your_database_name
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - api.internal

  nextjs:
    build:
      context: ./fe
    container_name: nextjs_app
    environment:
      NEXT_PUBLIC_API_URL: http://nestjs:3000
    ports:
      - "80:80"
    depends_on:
      - nestjs
    networks:
      - app_network

networks:
  app_network:
    name: hubbi-test_app_network
    driver: bridge
